#pragma once
#include "NativeGameplayTags.h"

namespace CoreGameplayTags
{
	namespace ADVMInputTags
	{
		COREFEATURES_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Action_Move);
		COREFEATURES_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Action_Look);
		COREFEATURES_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Action_Jump);
	}
	namespace InitStateTags
	{
		COREFEATURES_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InitState_Spawned);
		COREFEATURES_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InitState_DataAvaliable);
		COREFEATURES_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InitState_DataInitialized);
		COREFEATURES_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InitState_GameplayReady);
	}

	namespace InventoryTags
	{
		COREFEATURES_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_Stat_MaxStackSize);
		COREFEATURES_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_Stat_Weight);
		COREFEATURES_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_Stat_BaseValue);
		
		COREFEATURES_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_State_StackCount);
		COREFEATURES_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_State_Durability);
		COREFEATURES_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_State_Level);
		
		COREFEATURES_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_Type_Weapon);
		COREFEATURES_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_Type_Consumable);
		COREFEATURES_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_Type_Material);
		
		COREFEATURES_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_Slot_PrimaryWeapon);
		COREFEATURES_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_Slot_SecondaryWeapon);
		COREFEATURES_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_Slot_Backpack);
		COREFEATURES_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_Slot_Head);
		COREFEATURES_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_Slot_Chest);
		
		COREFEATURES_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Inventory_ItemAdded);
		COREFEATURES_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Inventory_ItemRemoved);
	}
};
